[pycodestyle]
max_line_length = 120
ignore = E501,W601

[metadata]
name = PyAfipWs
version = nybble.1.0.dev
description = Interfases, tools and apps for Argentina's gov't. webservices
long_description = file: README.md
long_description_content_type = text/markdown
author = Mariano Reingart
author_email = reingart@gmail.com
url = https://github.com/nybblegroup/bs-pyafipws
license = GNU GPL v3+
classifiers = 
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    Intended Audience :: End Users/Desktop
    Intended Audience :: Financial and Insurance Industry
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Operating System :: OS Independent
    Operating System :: Microsoft :: Windows
    Natural Language :: Spanish
    Topic :: Office/Business :: Financial :: Point-Of-Sale
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Software Development :: Object Brokering
keywords = webservice electronic invoice pdf traceability

[options]
packages = find:
package_dir = 
    pyafipws = .
python_requires = >=3.6
install_requires = 
    httplib2>=0.12.0
    m2crypto>=0.18
    fpdf>=1.7.2
    dbf>=0.88.019
    Pillow>=2.0.0
    certifi>=2020.4.5.1

[options.packages.find]
include = pyafipws*

[options.package_data]
pyafipws = 
    plantillas/*
    conf/*
    *.py

